spring.application.name: art-brewery-gateway
server.port: 9090
net.shyshkin.routes:
  beer-service: http://localhost:8080
  beer-order-service: http://localhost:8081
  beer-inventory-service: http://localhost:8082
logging:
  level:
    org.springframework.cloud.gateway: debug
spring:
  zipkin:
    enabled: true
  sleuth:
    reactor:
      instrumentation-type: decorate_on_each # Less performing and deprecated. Will be removed in Sleuth 4.0.0
---
spring:
  config:
    activate:
      on-profile:
        - local-discovery
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://EurekaUser:EurekaSuperSecretPass@localhost:8761/eureka