version: '3.8'

services:

#  docker run -it --rm -p 8161:8161 -p 61616:61616 vromero/activemq-artemis
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616

#  docker run -d -p 9411:9411 openzipkin/zipkin
  zipkin:
    image: openzipkin/zipkin
    ports: ["9411:9411"]

  eureka:
    image: artarkatesoft/art-sfg-mssc-brewery-eureka
    ports:
      - 8761:8761
#    healthcheck: # because curl is not present
#      test: ["CMD", "curl", "-f", "http://EurekaUser:EurekaSuperSecretPass@eureka:8761/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  config:
    image: artarkatesoft/art-sfg-mssc-config-server
    ports:
      - 8888:8888 # Actually not needed because docker-compose creates network "compose_default" with the default driver and we do not need to expose port
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://EurekaUser:EurekaSuperSecretPass@eureka:8761/eureka

  inventory-service:
    image: artarkatesoft/beer-inventory-service
    ports: ["8082:8082"]
    depends_on:
      - eureka
      - config
      - jms
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://EurekaUser:EurekaSuperSecretPass@eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql,base_log
#      SPRING_PROFILES_ACTIVE: local-discovery,local,base_log #We can not override Cloud Config Property (by default)
      SPRING_CLOUD_DISCOVERY_ENABLED: 'true'  # localmysql profile disables discovery - we need to switch it on
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      SPRING_CLOUD_CONFIG_FAIL_FAST: 'true'
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: 'true'   # TODO: fix this Error


