version: '3.8'

services:

  filebeat:
    image: artarkatesoft/mssc-filebeat:7.10.1
    volumes:
      -  /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      -  /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    extra_hosts:
      - "elasticsearch:10.114.16.5"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure


