version: '3.7'

services:

  filebeat:
    image: artarkatesoft/mssc-filebeat:7.10.1
    volumes:
      -  /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      -  /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    extra_hosts:
      - "elasticsearch:10.114.16.5"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  inventory-service:
    image: artarkatesoft/beer-inventory-service
    ports: ["8082:8082"]
    restart: on-failure
    depends_on:
      - filebeat
    environment:
      SPRING_PROFILES_ACTIVE: 'digitalocean'
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"service-url":{"defaultZone":"http://EurekaUser:EurekaSuperSecretPass@10.114.16.6:8761/eureka"},"region":"default","register-with-eureka":true},"instance":{"prefer-ip-address":false,"hostname":"inventory-service"}},"spring":{"cloud":{"config":{"enabled":true,"fail-fast":true,"username":"MyUserName","password":"MySecretPassword","discovery":{"enabled":true,"service-id":"mssc-brewery-config"}},"discovery":{"enabled":true}}}}'
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2

  inventory-failover:
    image: artarkatesoft/beer-inventory-failover
    ports: ["8083:8083"]
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"service-url":{"defaultZone":"http://EurekaUser:EurekaSuperSecretPass@10.114.16.6:8761/eureka"},"region":"default","register-with-eureka":true},"instance":{"prefer-ip-address":false,"hostname":"inventory-failover"}},"spring":{"cloud":{"config":{"enabled":true,"fail-fast":true,"username":"MyUserName","password":"MySecretPassword","discovery":{"enabled":true,"service-id":"mssc-brewery-config"}},"discovery":{"enabled":true}}}}'
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'
    deploy:
      replicas: 2

  beer-service:
    image: artarkatesoft/beer-service
    ports: ["8080:8080"]
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: 'digitalocean'
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"service-url":{"defaultZone":"http://EurekaUser:EurekaSuperSecretPass@10.114.16.6:8761/eureka"},"region":"default","register-with-eureka":true},"instance":{"prefer-ip-address":false,"hostname":"beer-service"}},"spring":{"cloud":{"config":{"enabled":true,"fail-fast":true,"username":"MyUserName","password":"MySecretPassword","discovery":{"enabled":true,"service-id":"mssc-brewery-config"}},"discovery":{"enabled":true}}}}'
    depends_on:
      - inventory-service
      - inventory-failover
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2

  beer-order-service:
    image: artarkatesoft/beer-order-service
    ports: ["8081:8081"]
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: 'digitalocean,base_log,local-discovery'
#      NET_SHYSHKIN_CLIENT_BEER_SERVICE_HOST: 'http://beer-service'
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"service-url":{"defaultZone":"http://EurekaUser:EurekaSuperSecretPass@10.114.16.6:8761/eureka"},"region":"default","register-with-eureka":true},"instance":{"prefer-ip-address":false,"hostname":"beer-order-service"}},"spring":{"cloud":{"config":{"enabled":true,"fail-fast":true,"username":"MyUserName","password":"MySecretPassword","discovery":{"enabled":true,"service-id":"mssc-brewery-config"}},"discovery":{"enabled":true}}}}'
    depends_on:
      - beer-service
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 2

  gateway:
    image: artarkatesoft/art-sfg-mssc-brewery-gateway
    ports: ["9090:9090"]
    environment:
      SPRING_PROFILES_ACTIVE: 'local-discovery'
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"service-url":{"defaultZone":"http://EurekaUser:EurekaSuperSecretPass@10.114.16.6:8761/eureka"},"region":"default","register-with-eureka":false},"instance":{"prefer-ip-address":true}}}'
      SPRING_ZIPKIN_BASEURL: http://10.114.16.9:9411
    depends_on:
      - inventory-service
      - beer-service
      - beer-order-service
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'
    deploy:
      replicas: 2

  tasting-room-service:
    image: artarkatesoft/beer-tasting-room-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: 'digitalocean'
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"service-url":{"defaultZone":"http://EurekaUser:EurekaSuperSecretPass@10.114.16.6:8761/eureka"},"region":"default","register-with-eureka":true},"instance":{"prefer-ip-address":false,"hostname":"tasting-room-service"}},"spring":{"cloud":{"config":{"enabled":true,"fail-fast":true,"username":"MyUserName","password":"MySecretPassword","discovery":{"enabled":true,"service-id":"mssc-brewery-config"}},"discovery":{"enabled":true}}}}'
    depends_on:
      - eureka
      - config
      - beer-service
      - beer-order-service
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'
    deploy:
      replicas: 3