version: '3.8'

services:

#  docker run -it --rm -p 8161:8161 -p 61616:61616 vromero/activemq-artemis
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616

#  docker run -d -p 9411:9411 openzipkin/zipkin
  zipkin:
    image: openzipkin/zipkin
    ports: ["9411:9411"]

